      - name: Install dependencies
        run: npm install
        working-directory: /users/gabri/comp2156/

      - name: Run tests
        run: npm test
        working-directory: /users/gabri/comp2156/

